### PR TITLE
Trying different image to get twitter card working

### PR DESCRIPTION
**Pull request by actlatham**

### CODE REVIEW

**Comment by joerick** [comment]
You can do alt tags on divs? I thought they were only for img tags?

**Comment by actlatham** [comment]
mmmm let me check
ᐧ

On Tue, Mar 22, 2016 at 4:41 PM, Joe Rickerby notifications@github.com
wrote:

> You can do alt tags on divs? I thought they were only for img tags?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/getmixim/getmixim.com/pull/4#issuecomment-199896496

## 

_Alex Latham_

_Artist Managment_
_Au Mgmt_

_Phone: 07896777345_
_Email: alex@au-mgmt.com alex@au-mgmt.com_
_Follow me on Twitter @actlatham_

**Comment by joerick** [comment]
Do you know why the twitter image might not be working? I don't know how this is different.

**Comment by actlatham** [comment]
No it’s winding me up - the latest pull has it in exactly the right dimensions so unless that works I’m stumped

**Comment by actlatham** [comment]
you're right about the div's - thought we could for some reason . We don't
have any img tags on the page tho

ᐧ

On Tue, Mar 22, 2016 at 4:44 PM, Alex Latham alex@au-mgmt.com wrote:

> No it’s winding me up - the latest pull has it in exactly the right
> dimensions so unless that works I’m stumped
> 
> On 22 Mar 2016, at 16:43, Joe Rickerby notifications@github.com wrote:
> 
> Do you know why the twitter image might not be working? I don't know how
> this is different.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/getmixim/getmixim.com/pull/4#issuecomment-199897331

## 

_Alex Latham_

_Artist Managment_
_Au Mgmt_

_Phone: 07896777345_
_Email: alex@au-mgmt.com alex@au-mgmt.com_
_Follow me on Twitter @actlatham_

**Comment by joerick** [comment]
the svg tags could have alt tags perhaps? worth checking

**Pull request merged**
